# Generated by Django 4.2.2 on 2023-07-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userregister_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profregister',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='profregister',
            name='password2',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='password2',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='profilePic',
        ),
        migrations.AlterField(
            model_name='profregister',
            name='profilePic',
            field=models.ImageField(null=True, upload_to='professional_pic/'),
        ),
    ]
