# Generated by Django 4.2.2 on 2023-07-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_profregister_password1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='profilePic',
            field=models.ImageField(null=True, upload_to='customers_pic/'),
        ),
    ]
