# Generated by Django 4.2.2 on 2023-07-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_userregister_profilepic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profregister',
            name='service_selection',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='profregister',
            name='working_location',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
