# Generated by Django 4.2.2 on 2023-07-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_userregister_username_alter_userregister_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='user',
        ),
        migrations.AddField(
            model_name='userregister',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
