# Generated by Django 4.2.2 on 2023-07-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_userregister_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profregister',
            name='working_location',
        ),
        migrations.AlterField(
            model_name='profregister',
            name='profilePic',
            field=models.ImageField(null=True, upload_to='prof_pic/'),
        ),
        migrations.AlterField(
            model_name='profregister',
            name='service_selection',
            field=models.CharField(null=True),
        ),
    ]
