# Generated by Django 4.2.2 on 2023-07-10 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_profregister_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_date', models.DateField(null=True)),
                ('book_days', models.CharField(max_length=100, null=True)),
                ('book_hours', models.CharField(max_length=100, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.userregister')),
                ('professional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.profregister')),
            ],
        ),
    ]
