# Generated by Django 4.2.2 on 2023-07-13 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_service_profregister_city_profregister_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profregister',
            name='service_selection',
        ),
    ]
